# Chatbot Frontend configuration
chatbotFrontend:
  # Deployment name
  name: basedosdados-chatbot-frontend

  # Deployment image
  image:
    name: ghcr.io/basedosdados/chatbot-frontend
    tag: stable
    pullPolicy: Always

  # Number of replicas
  replicas: 1

  # Resource specification
  resources:
    requests:
      cpu: 1
      memory: 500Mi
    limits:
      cpu: 1
      memory: 1Gi

  # Ingress configuration
  ingress:
    # Enable ingress
    enabled: true

    # Host to be used in the ingress
    host: ""

    # Ingress annotations
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: true
      cert-manager.io/issuer: letsencrypt-production
    # TLS configuration
    tls:
      - hosts:
          - ""
        secretName: ""
