apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.chatbotFrontend.name }}
  labels:
    app.kubernetes.io/component: basedosdados-chatbot-frontend
    app.kubernetes.io/name: {{ .Values.chatbotFrontend.name }}
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
spec:
  replicas: {{ .Values.chatbotFrontend.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/component: basedosdados-chatbot-frontend
      app.kubernetes.io/name: {{ .Values.chatbotFrontend.name }}
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/component: basedosdados-chatbot-frontend
        app.kubernetes.io/name: {{ .Values.chatbotFrontend.name }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: basedosdados-chatbot-frontend
          image: "{{ .Values.chatbotFrontend.image.name }}:{{ .Values.chatbotFrontend.image.tag }}"
          imagePullPolicy: {{ .Values.chatbotFrontend.image.pullPolicy }}
          ports:
            - name: streamlit
              containerPort: 8501
          env:
            - name: WEBSITE_HOST
              value: {{ required ".Values.chatbotFrontend.env.WEBSITE_HOST is required" $env.WEBSITE_HOST | quote }}
            - name: WEBSITE_PORT
              value: {{ required ".Values.chatbotFrontend.env.WEBSITE_PORT is required" $env.WEBSITE_PORT | quote }}
            - name: CHATBOT_HOST
              value: {{ required ".Values.chatbotFrontend.env.CHATBOT_HOST is required" $env.CHATBOT_HOST | quote }}
            - name: CHATBOT_PORT
              value: {{ required ".Values.chatbotFrontend.env.CHATBOT_PORT is required" $env.CHATBOT_PORT | quote }}
          {{- with .Values.chatbotFrontend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 10
            periodSeconds: 10
      restartPolicy: Always
